services:
  apache:
    image: php:apache
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --skip-name-resolve 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - mysql

